export * from "./links"
export * from "./pagination"
export * from "./verbsResponse"
export * from "./regularVerbsRes"
export * from "./irregularVerbsRes"
export * from "./verbById"
export * from "./translations"
export * from "./verbsByWord"